spring.application.name=Capston2-BloodDonation
spring.datasource.url=jdbc:mysql://localhost:3306/blood_danation
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true